In [93]:
# Importing the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key
gmaps.configure(api_key=g_key)

In [2]:
# Importing the CSV created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/WeatherPy_Challenge.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches last 3 hours,Snow inches last 3 hours
0,0,Ribeira Grande,PT,2020-04-20 01:41:36,38.52,-28.70,56.26,58,2,7.27,clear sky,0.00,0.0
1,1,Torbay,CA,2020-04-20 01:41:36,47.67,-52.73,36.00,100,90,26.40,moderate rain,1.27,0.0
2,2,Laguna,US,2020-04-20 01:41:20,38.42,-121.42,68.00,48,1,5.82,clear sky,0.00,0.0
3,3,Moissala,TD,2020-04-20 01:41:37,8.34,17.77,80.55,55,89,5.61,overcast clouds,0.00,0.0
4,4,Brownsville,US,2020-04-20 01:41:37,25.90,-97.50,86.00,70,1,8.05,clear sky,0.00,0.0

In [68]:
# Adding columns to map raining and snowing conditions
def raining(col):
    if col > 0:
        return 'yes'
    else:
        return 'no'
    
def snowing(col):
    if col > 0:
        return 'yes'
    else:
        return 'no'

In [69]:
# Mapping columns
city_data_df['raining']=city_data_df['Rain inches last 3 hours'].apply(raining)
city_data_df['snowing']=city_data_df['Snow inches last 3 hours'].apply(raining)

In [70]:
city_data_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches last 3 hours,Snow inches last 3 hours,raining,snowing
0,0,Ribeira Grande,PT,2020-04-20 01:41:36,38.52,-28.70,56.26,58,2,7.27,clear sky,0.00,0,no,no
1,1,Torbay,CA,2020-04-20 01:41:36,47.67,-52.73,36.00,100,90,26.40,moderate rain,1.27,0,yes,no
2,2,Laguna,US,2020-04-20 01:41:20,38.42,-121.42,68.00,48,1,5.82,clear sky,0.00,0,no,no
3,3,Moissala,TD,2020-04-20 01:41:37,8.34,17.77,80.55,55,89,5.61,overcast clouds,0.00,0,no,no
4,4,Brownsville,US,2020-04-20 01:41:37,25.90,-97.50,86.00,70,1,8.05,clear sky,0.00,0,no,no
5,5,Deputatskiy,RU,2020-04-20 01:41:38,69.30,139.90,9.95,87,26,6.20,scattered clouds,0.00,0,no,no
6,6,Kasongo,CD,2020-04-20 01:41:38,-4.45,26.67,67.59,83,88,1.90,light rain,1.23,0,yes,no
7,7,Caravelas,BR,2020-04-20 01:41:38,-17.71,-39.25,74.89,78,15,13.18,few clouds,0.00,0,no,no
8,8,Fukue,JP,2020-04-20 01:41:38,32.69,128.84,60.80,72,75,11.41,broken clouds,0.00,0,no,no
9,9,Teya,RU,2020-04-20 01:41:39,60.38,92.63,38.68,63,97,7.85,overcast clouds,0.00,0,no,no

In [72]:
# Creating input fields to ask the customer to add preferences.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))
rain_ask = str(input("Do you want it to be raining? (yes/no) "))
snow_ask = str(input("Do you want it to be snowing? (yes/no) "))

What is the minimum temperature you would like for your trip? 70
What is the maximum temperature you would like for your trip? 90
Do you want it to be raining? (yes/no) yes
Do you want it to be snowing? (yes/no) no

In [78]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp) &
                                       (city_data_df["raining"] == rain_ask) &
                                       (city_data_df["snowing"] == snow_ask)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches last 3 hours,Snow inches last 3 hours,raining,snowing
49,49,Poum,NC,2020-04-20 01:41:50,-20.23,164.02,80.60,76,100,8.79,light rain,0.89,0,yes,no
56,56,Almeirim,BR,2020-04-20 01:41:51,-1.52,-52.58,73.69,97,100,2.84,light rain,0.41,0,yes,no
69,69,Sambava,MG,2020-04-20 01:41:55,-14.27,50.17,73.31,87,100,5.82,light rain,0.60,0,yes,no
83,83,Micheweni,TZ,2020-04-20 01:41:59,-4.97,39.83,80.53,78,100,15.43,light rain,1.87,0,yes,no
103,103,Yako,BF,2020-04-20 01:42:04,12.97,-2.27,85.59,41,97,11.50,light rain,0.18,0,yes,no
118,118,Alta Floresta,BR,2020-04-20 01:42:07,-9.88,-56.09,71.78,87,100,1.43,light rain,1.39,0,yes,no
122,122,Axim,GH,2020-04-20 01:37:42,4.87,-2.24,81.27,82,100,6.38,light rain,0.81,0,yes,no
131,131,Sorong,ID,2020-04-20 01:42:11,-0.88,131.25,88.63,68,10,0.51,light rain,0.94,0,yes,no
142,142,Faanui,PF,2020-04-20 01:42:14,-16.48,-151.75,82.24,77,81,19.19,light rain,1.20,0,yes,no
154,154,Harper,LR,2020-04-20 01:42:17,4.38,-7.72,80.53,84,100,4.99,light rain,0.58,0,yes,no

In [80]:
# Creating a new DataFrame with hotels to store hotel names along with existing data.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng", "Current Description"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Current Description,Hotel Name
49,Poum,NC,80.60,-20.23,164.02,light rain,
56,Almeirim,BR,73.69,-1.52,-52.58,light rain,
69,Sambava,MG,73.31,-14.27,50.17,light rain,
83,Micheweni,TZ,80.53,-4.97,39.83,light rain,
103,Yako,BF,85.59,12.97,-2.27,light rain,
118,Alta Floresta,BR,71.78,-9.88,-56.09,light rain,
122,Axim,GH,81.27,4.87,-2.24,light rain,
131,Sorong,ID,88.63,-0.88,131.25,light rain,
142,Faanui,PF,82.24,-16.48,-151.75,light rain,
154,Harper,LR,80.53,4.38,-7.72,light rain,

In [81]:
# Setting parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [82]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
       
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [84]:
hotel_df.head()

,City,Country,Max Temp,Lat,Lng,Current Description,Hotel Name
49,Poum,NC,80.60,-20.23,164.02,light rain,Gîte kajeon
56,Almeirim,BR,73.69,-1.52,-52.58,light rain,Ricácio Hotel
69,Sambava,MG,73.31,-14.27,50.17,light rain,Melrose
83,Micheweni,TZ,80.53,-4.97,39.83,light rain,
103,Yako,BF,85.59,12.97,-2.27,light rain,Ecole de Sibega

In [85]:
# Defining the info in the pop-up marker
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
<dt>Current Weather</dt><dd>{Current Description}</dd>
</dl>
"""

In [98]:
# Storing the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
hotel_info

['\n<dl>\n<dt>Hotel Name</dt><dd>Gîte kajeon</dd>\n<dt>City</dt><dd>Poum</dd>\n<dt>Country</dt><dd>NC</dd>\n<dt>Max Temp</dt><dd>80.6 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Ricácio Hotel</dd>\n<dt>City</dt><dd>Almeirim</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Max Temp</dt><dd>73.69 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Melrose</dd>\n<dt>City</dt><dd>Sambava</dd>\n<dt>Country</dt><dd>MG</dd>\n<dt>Max Temp</dt><dd>73.31 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd></dd>\n<dt>City</dt><dd>Micheweni</dd>\n<dt>Country</dt><dd>TZ</dd>\n<dt>Max Temp</dt><dd>80.53 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Ecole de Sibega</dd>\n<dt>City</dt><dd>Yako</dd>\n<dt>Country</dt><dd>BF</dd>\n<dt>Max Temp</dt><dd>85.59 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Floresta Amazonica Hotel</dd>\n<dt>City</dt><dd>Alta Floresta</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Max Temp</dt><dd>71.78 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>AXIM BEACH RESORT AND SPA</dd>\n<dt>City</dt><dd>Axim</dd>\n<dt>Country</dt><dd>GH</dd>\n<dt>Max Temp</dt><dd>81.27 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>The Waigo Hotel</dd>\n<dt>City</dt><dd>Sorong</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Max Temp</dt><dd>88.63 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Bora-Bora Pearl Beach Resort & Spa</dd>\n<dt>City</dt><dd>Faanui</dd>\n<dt>Country</dt><dd>PF</dd>\n<dt>Max Temp</dt><dd>82.24 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Cape View Guest House</dd>\n<dt>City</dt><dd>Harper</dd>\n<dt>Country</dt><dd>LR</dd>\n<dt>Max Temp</dt><dd>80.53 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel da Amazônia</dd>\n<dt>City</dt><dd>Borba</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Max Temp</dt><dd>73.62 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Kanyapur</dd>\n<dt>City</dt><dd>Tezpur</dd>\n<dt>Country</dt><dd>IN</dd>\n<dt>Max Temp</dt><dd>79.05 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Circuit House</dd>\n<dt>City</dt><dd>Tezu</dd>\n<dt>Country</dt><dd>IN</dd>\n<dt>Max Temp</dt><dd>70.41 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Isles Sunset Lodge</dd>\n<dt>City</dt><dd>Butaritari</dd>\n<dt>Country</dt><dd>KI</dd>\n<dt>Max Temp</dt><dd>83.77 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Residences David Hebié</dd>\n<dt>City</dt><dd>Banfora</dd>\n<dt>Country</dt><dd>BF</dd>\n<dt>Max Temp</dt><dd>81.93 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Maitai Lapita Village Huahine</dd>\n<dt>City</dt><dd>Fare</dd>\n<dt>Country</dt><dd>PF</dd>\n<dt>Max Temp</dt><dd>83.46 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Nusa Island Retreat</dd>\n<dt>City</dt><dd>Kavieng</dd>\n<dt>Country</dt><dd>PG</dd>\n<dt>Max Temp</dt><dd>84.33 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd></dd>\n<dt>City</dt><dd>Kieta</dd>\n<dt>Country</dt><dd>PG</dd>\n<dt>Max Temp</dt><dd>83.73 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Raybow International Hotel</dd>\n<dt>City</dt><dd>Takoradi</dd>\n<dt>Country</dt><dd>GH</dd>\n<dt>Max Temp</dt><dd>81.05 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd></dd>\n<dt>City</dt><dd>Merauke</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Max Temp</dt><dd>89.24 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Volcano Sea View Tree House</dd>\n<dt>City</dt><dd>Isangel</dd>\n<dt>Country</dt><dd>VU</dd>\n<dt>Max Temp</dt><dd>79.81 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel GSA</dd>\n<dt>City</dt><dd>Santa Isabel Do Rio Negro</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Max Temp</dt><dd>74.32 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Camp Pasica</dd>\n<dt>City</dt><dd>Dingle</dd>\n<dt>Country</dt><dd>PH</dd>\n<dt>Max Temp</dt><dd>89.37 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Piaçabuçu News</dd>\n<dt>City</dt><dd>Piacabucu</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Max Temp</dt><dd>78.4 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Pousada Tropical</dd>\n<dt>City</dt><dd>Barra Do Garcas</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Max Temp</dt><dd>73.06 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>JAIRO ORLINDO VIEIRA</dd>\n<dt>City</dt><dd>Itupiranga</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Max Temp</dt><dd>78.8 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>LES EAUX DE KILISSI</dd>\n<dt>City</dt><dd>Kindia</dd>\n<dt>Country</dt><dd>GN</dd>\n<dt>Max Temp</dt><dd>73.83 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>ALETHEIA Appartement Sinnamary</dd>\n<dt>City</dt><dd>Sinnamary</dd>\n<dt>Country</dt><dd>GF</dd>\n<dt>Max Temp</dt><dd>78.67 °F</dd>\n<dt>Current Weather</dt><dd>moderate rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Zal-Ann Beach Resort</dd>\n<dt>City</dt><dd>San Policarpo</dd>\n<dt>Country</dt><dd>PH</dd>\n<dt>Max Temp</dt><dd>83.21 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Maqna Hotel by Prasanthi</dd>\n<dt>City</dt><dd>Gorontalo</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Max Temp</dt><dd>86.0 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>hotêl doufoulougou</dd>\n<dt>City</dt><dd>Tabou</dd>\n<dt>Country</dt><dd>CI</dd>\n<dt>Max Temp</dt><dd>79.88 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Airport Lodge Kiunga</dd>\n<dt>City</dt><dd>Kiunga</dd>\n<dt>Country</dt><dd>PG</dd>\n<dt>Max Temp</dt><dd>89.67 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Lorengau Harbourside Hotel</dd>\n<dt>City</dt><dd>Lorengau</dd>\n<dt>Country</dt><dd>PG</dd>\n<dt>Max Temp</dt><dd>84.49 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Sentinel</dd>\n<dt>City</dt><dd>Port Blair</dd>\n<dt>Country</dt><dd>IN</dd>\n<dt>Max Temp</dt><dd>84.47 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Kou-Bugny</dd>\n<dt>City</dt><dd>Vao</dd>\n<dt>Country</dt><dd>NC</dd>\n<dt>Max Temp</dt><dd>73.98 °F</dd>\n<dt>Current Weather</dt><dd>heavy intensity rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>MHL Turismo SA</dd>\n<dt>City</dt><dd>Inhambane</dd>\n<dt>Country</dt><dd>MZ</dd>\n<dt>Max Temp</dt><dd>72.72 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>VS Villa</dd>\n<dt>City</dt><dd>Kalmunai</dd>\n<dt>Country</dt><dd>LK</dd>\n<dt>Max Temp</dt><dd>85.73 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Praia Dourada</dd>\n<dt>City</dt><dd>Maragogi</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Max Temp</dt><dd>78.94 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Savannah Inn</dd>\n<dt>City</dt><dd>Lethem</dd>\n<dt>Country</dt><dd>GY</dd>\n<dt>Max Temp</dt><dd>80.24 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Derogongan Residence</dd>\n<dt>City</dt><dd>Marawi</dd>\n<dt>Country</dt><dd>PH</dd>\n<dt>Max Temp</dt><dd>82.49 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Auberge les abou</dd>\n<dt>City</dt><dd>Fomboni</dd>\n<dt>Country</dt><dd>KM</dd>\n<dt>Max Temp</dt><dd>82.62 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Al Shohada Hotel MAKKAH</dd>\n<dt>City</dt><dd>Mecca</dd>\n<dt>Country</dt><dd>SA</dd>\n<dt>Max Temp</dt><dd>72.68 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Chik-Chik Namibe</dd>\n<dt>City</dt><dd>Namibe</dd>\n<dt>Country</dt><dd>AO</dd>\n<dt>Max Temp</dt><dd>74.39 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Citra</dd>\n<dt>City</dt><dd>Sabang</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Max Temp</dt><dd>84.6 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Leopards courier mirpur mathelo</dd>\n<dt>City</dt><dd>Mirpur Mathelo</dd>\n<dt>Country</dt><dd>PK</dd>\n<dt>Max Temp</dt><dd>84.43 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Vahmoneh Lodge Vanimo</dd>\n<dt>City</dt><dd>Vanimo</dd>\n<dt>Country</dt><dd>PG</dd>\n<dt>Max Temp</dt><dd>81.81 °F</dd>\n<dt>Current Weather</dt><dd>moderate rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Taloa Heights</dd>\n<dt>City</dt><dd>Alofi</dd>\n<dt>Country</dt><dd>NU</dd>\n<dt>Max Temp</dt><dd>84.2 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>InterContinental Riyadh</dd>\n<dt>City</dt><dd>Riyadh</dd>\n<dt>Country</dt><dd>SA</dd>\n<dt>Max Temp</dt><dd>73.4 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>HOTEL "SAN JOSE"</dd>\n<dt>City</dt><dd>San Matias</dd>\n<dt>Country</dt><dd>BO</dd>\n<dt>Max Temp</dt><dd>73.89 °F</dd>\n<dt>Current Weather</dt><dd>light rain</dd>\n</dl>\n']

In [94]:
# Adding a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [97]:
# Creating the output file (CSV).
output_data_file = "weather_data/WeatherPy_Vacation.csv"
# Export the City_Data into a CSV.
hotel_df.to_csv(output_data_file, index_label="City_ID")